name: CICD

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0' # The Go version to download (if necessary) and use.

      # Run build of the application
      - name: Run build
        run: go build -o aws-ses-bounce-handler main.go

      - uses: actions/upload-artifact@v2
        with:
          name: aws-ses-bounce-handler
          path: aws-ses-bounce-handler